Realtime Survey/src/hotmess/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^surveys/", include("surveys.urls", namespace="surveys")),
    url(r"^$", TemplateView.as_view(template_name="hotmess/index.html"), name="index"),
]

Realtime Survey/src/surveys/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from .views import (
    SurveyStage1View,
    SurveyStage2View,
    SurveyStage3View,
    SurveyStage4View
)

urlpatterns = [
    url(r"^$", SurveyStage1View.as_view(), name="stage-1"),
    url(r"^2$", SurveyStage2View.as_view(), name="stage-2"),
    url(r"^3$", SurveyStage3View.as_view(), name="stage-3"),
    url(r"^4$", SurveyStage4View.as_view(), name="stage-4"),
    url(r"^thanks$", TemplateView.as_view(template_name="surveys/thanks.html"), name="thanks"),
]

Realtime Survey/src/hotmess/forms.py
from django import forms


class BootstrapMixin:
    """
    A simple way to have Django generate form fields with bootstrappy classes
    attached to them.
    """

    # Don't apply `form-control` to these fields
    UNCONTROLLED_FIELDS = (
        forms.widgets.RadioSelect,
        forms.widgets.CheckboxInput,
        forms.widgets.CheckboxSelectMultiple,
        forms.widgets.FileInput
    )

    def _bootstrapify(self):

        for field_name in self.fields.keys():

            widget = self.fields[field_name].widget

            self.fields[field_name].label_suffix = ""
            if not isinstance(widget, self.UNCONTROLLED_FIELDS):
                widget.attrs.update({"class": "form-control"})

Realtime Survey/src/hotmess/templates/hotmess/base.html
{% load staticfiles sexy %}<!DOCTYPE html>
<html>
	<head>
		<title>Hot Mess</title>
		{% block css %}
			<link rel="stylesheet" href="{% static 'contrib/css/bootstrap.min.css' %}" />
			<link rel="stylesheet" href="{% static 'contrib/css/open-iconic-bootstrap.min.css' %}">
			<style>
				body {
					background: url("{% random_background %}") no-repeat center center fixed;
					-webkit-background-size: cover;
					-moz-background-size: cover;
					-o-background-size: cover;
					background-size: cover;
				}
				.page {
					background-color: rgba(255, 255, 255, 0.8);
					border-radius: 2rem;
					padding: 1rem;
					margin-top: 1rem;
				}
			</style>
		{% endblock css %}
		{% block js_header %}
			<script src="{% static 'contrib/js/jquery-3.2.1.min.js' %}"></script>
			<script src="{% static 'contrib/js/popper.js' %}"></script>
			<script src="{% static 'contrib/js/bootstrap.min.js' %}"></script>
		{% endblock js_header %}
	</head>
	<body>
		<div class="container page">
			{% block content %}{% endblock content %}
		</div>
		{% block js_footer %}{% endblock js_footer %}
	</body>
</html>

Realtime Survey/src/hotmess/templates/hotmess/index.html
{% extends 'hotmess/base.html' %}


{% block content %}

	<div class="container">

		<div class="row">
			<div class="col-sm">
				<h1 class="display-1 text-center">Wanna Do the Thing?</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm text-center">
				<a href="{% url 'surveys:stage-1' %}" class="btn btn-primary" style="margin-top: 2rem;">Do the thing</a>
			</div>
		</div>

	</div>

{% endblock content %}